# app/models/team_data.py

TEAM_NAMES = {
    "Spartak Moscow": "Спартак", "Dinamo Moscow": "Динамо", "CSKA Moscow": "ЦСКА",
    "Zenit St. Petersburg": "Зенит", "Lokomotiv Moscow": "Локомотив", "FC Krasnodar": "Краснодар",
    "FK Akhmat": "Ахмат", "FC Rostov": "Ростов", "Rubin Kazan": "Рубин",
    "Krylya Sovetov Samara": "Крылья Советов", "Nizhny Novgorod": "Пари НН",
    "FC Orenburg": "Оренбург", "Baltika": "Балтика", "PFC Sochi": "Сочи",
    "Dynamo Makhachkala": "Динамо Мх", "Akron": "Акрон",
    "Mexico": "Мексика", "South Africa": "ЮАР", "South Korea": "Южная Корея",
    "Czechia": "Чехия", "Canada": "Канада", "Bosnia-Herzegovina": "Босния и Герцеговина",
    "United States": "США", "Paraguay": "Парагвай", "Qatar": "Катар", "Switzerland": "Швейцария",
    "Brazil": "Бразилия", "Morocco": "Марокко", "Haiti": "Гаити", "Scotland": "Шотландия",
    "Australia": "Австралия", "Turkey": "Турция", "Germany": "Германия", "Curaçao": "Кюрасао",
    "Netherlands": "Нидерланды", "Japan": "Япония", "Ivory Coast": "Кот-д'Ивуар",
    "Ecuador": "Эквадор", "Sweden": "Швеция", "Tunisia": "Тунис", "Spain": "Испания",
    "Cape Verde Islands": "Кабо-Верде", "Belgium": "Бельгия", "Egypt": "Египет",
    "Saudi Arabia": "Саудовская Аравия", "Uruguay": "Уругвай", "Iran": "Иран",
    "New Zealand": "Новая Зеландия", "France": "Франция", "Senegal": "Сенегал",
    "Iraq": "Ирак", "Norway": "Норвегия", "Argentina": "Аргентина", "Algeria": "Алжир",
    "Austria": "Австрия", "Jordan": "Иордания", "Portugal": "Португалия", "Congo DR": "ДР Конго",
    "England": "Англия", "Croatia": "Хорватия", "Ghana": "Гана", "Panama": "Панама",
    "Uzbekistan": "Узбекистан", "Colombia": "Колумбия",
    "Russia": "Россия",
    "Burkina Faso": "Буркина-Фасо",
    "Trinidad and Tobago": "Тринидад и Тобаго",
}

TEAM_FLAGS = {
    "Россия": "ru", "Бразилия": "br", "Аргентина": "ar", "Германия": "de",
    "Франция": "fr", "Испания": "es", "Англия": "gb-eng", "Италия": "it",
    "Нидерланды": "nl", "Португалия": "pt", "Бельгия": "be", "Хорватия": "hr",
    "Уругвай": "uy", "Колумбия": "co", "Мексика": "mx", "США": "us",
    "Япония": "jp", "Южная Корея": "kr", "Сенегал": "sn", "Марокко": "ma",
    "Египет": "eg", "Саудовская Аравия": "sa", "Катар": "qa", "Австралия": "au",
    "Канада": "ca", "Швейцария": "ch", "Швеция": "se", "Норвегия": "no",
    "Турция": "tr", "Австрия": "at", "Чехия": "cz", "Иран": "ir",
    "Ирак": "iq", "Алжир": "dz", "Гана": "gh", "Панама": "pa",
    "Парагвай": "py", "Эквадор": "ec", "Тунис": "tn", "ЮАР": "za",
    "Шотландия": "gb-sct", "Гаити": "ht", "Босния и Герцеговина": "ba",
    "Кюрасао": "cw", "Кот-д'Ивуар": "ci", "Новая Зеландия": "nz",
    "Кабо-Верде": "cv", "Узбекистан": "uz", "ДР Конго": "cd", "Иордания": "jo",
    "Буркина-Фасо": "bf",
    "Тринидад и Тобаго": "tt",
}

CLUB_LOGOS = {
    "Спартак": "/static/clubs/spartak-moscow-footballlogos-org.png",
    "Динамо": "/static/clubs/dynamo-moscow-footballlogos-org.png",
    "ЦСКА": "/static/clubs/cska-moscow-footballlogos-org.png",
    "Зенит": "/static/clubs/zenit-saint-petersburg-footballlogos-org.png",
    "Локомотив": "/static/clubs/lokomotiv-moscow-footballlogos-org.png",
    "Краснодар": "/static/clubs/krasnodar-footballlogos-org.png",
    "Ахмат": "/static/clubs/akhmat-grozny-footballlogos-org.png",
    "Ростов": "/static/clubs/rostov-footballlogos-org.png",
    "Рубин": "/static/clubs/rubin-kazan-footballlogos-org.png",
    "Крылья Советов": "/static/clubs/krylia-sovetov-footballlogos-org.png",
    "Пари НН": "/static/clubs/pari-nn-footballlogos-org.png",
    "Оренбург": "/static/clubs/orenburg-footballlogos-org.png",
    "Балтика": "/static/clubs/baltika-kaliningrad-footballlogos-org.png",
    "Сочи": "/static/clubs/sochi-footballlogos-org.png",
    "Динамо Мх": "/static/clubs/dynamo-makhachkala-footballlogos-org.png",
    "Акрон": "/static/clubs/akron-togliatti-footballlogos-org.png",
}